import PIECE_COMPONENT_TYPE from '../../declaration_types/PieceComponent';

export const mockData: PIECE_COMPONENT_TYPE[] = [
  {
    id: 'circle-1',
    type: 'circle',
    title: 'Qualifié',
    icon: '',
    startColor: '#67e0d7',
    endColor: '#67e0d7',
    points: 10,
    delay: 0,
  },
  {
    id: 'stick-1',
    type: 'stick',
    startColor: '#67e0d7',
    endColor: '#7fd2fd',
    points: 20,
    delay: 0.2,
  },
  {
    id: 'circle-2',
    type: 'circle',
    title: 'Contacté',
    icon: '',
    startColor: '#7fd2fd',
    endColor: '#7fd2fd',
    points: 20,
    delay: 0.4,
  },
  {
    id: 'stick-2',
    type: 'stick',
    startColor: '#7fd2fd',
    endColor: '#49b2e7',
    points: 30,
    delay: 0.6,
  },
  {
    id: 'circle-3',
    type: 'circle',
    title: 'Présentation effectuée',
    icon: '',
    startColor: '#49b2e7',
    endColor: '#49b2e7',
    points: 30,
    delay: 0.8,
  },
  {
    id: 'stick-3',
    type: 'stick',
    startColor: '#49b2e7',
    endColor: '#ed7348',
    points: 40,
    delay: 1,
  },
  {
    id: 'circle-4',
    type: 'circle',
    title: 'Devis envoyé',
    icon: '',
    startColor: '#ed7348',
    endColor: '#ed7348',
    points: 40,
    delay: 1.2,
  },
];
