import PIECE_COMPONENT_TYPE from '../../declaration_types/PieceComponent';

export const mockData: PIECE_COMPONENT_TYPE[] = [
  {
    id: 'stick-7',
    type: 'stick',
    style: {
      width: 100,
    },
    startColor: '#0ab7af',
    endColor: '#0ab7af',
    points: 50,
    delay: 1.6,
  },
  {
    id: 'circle-5',
    type: 'circle',
    title: 'Intéressé',
    icon: '',
    startColor: '#0ab7af',
    endColor: '#0ab7af',
    points: 50,
    delay: 1.8,
  },
  {
    id: 'stick-8',
    type: 'stick',
    startColor: '#0ab7af',
    endColor: '#0ab7af',
    points: 50,
    delay: 2,
  },
  {
    id: 'circle-6',
    type: 'circle',
    title: 'Prospect chaud',
    icon: '',
    startColor: '#0ab7af',
    endColor: '#0ab7af',
    points: 50,
    delay: 2.2,
  },
  {
    id: 'stick-9',
    type: 'stick',
    startColor: '#0ab7af',
    endColor: '#0ab7af',
    points: 60,
    delay: 2.4,
  },
  {
    id: 'circle-7',
    type: 'circle',
    title: 'Convention signée',
    icon: '',
    startColor: '#0ab7af',
    endColor: '#0ab7af',
    points: 60,
    delay: 2.6,
  },
  {
    id: 'stick-10',
    type: 'stick',
    startColor: '#0ab7af',
    endColor: '#0ab7af',
    points: 70,
    delay: 2.8,
  },
  {
    id: 'circle-8',
    type: 'circle',
    title: 'Facturation accusée',
    icon: '',
    startColor: '#0ab7af',
    endColor: '#0ab7af',
    points: 70,
    delay: 3,
  },
  {
    id: 'stick-11',
    type: 'stick',
    startColor: '#0ab7af',
    endColor: '#00968f',
    points: 80,
    delay: 3.2,
  },
  {
    id: 'circle-9',
    type: 'circle',
    title: 'Paiement reçu',
    icon: '',
    startColor: '#00968f',
    endColor: '#00968f',
    points: 80,
    delay: 3.4,
  },
  {
    id: 'stick-12',
    type: 'stick',
    startColor: '#fcc201',
    endColor: '#fee302',
    points: 100,
    delay: 3.6,
  },
  {
    id: 'circle-10',
    type: 'circle',
    title: 'Dossier complété',
    icon: '',
    startColor: '#fee302',
    endColor: '#fee302',
    points: 100,
    delay: 3.8,
  },
];
